### ISSUE TITLE
view login tidak ada

### ISSUE THREAD

**Issue by vaniamc** [njiipanji/silkmm_rk#4]
![image](https://cloud.githubusercontent.com/assets/19382347/26140317/461db842-3b00-11e7-8d3f-e31a4bc5c585.png)

**Comment by njiipanji** [comment]
Sudah ditambahkan van

**Comment by njiipanji** [comment]
Sudah ditambahkan van, coba cek lagi

**Comment by vaniamc** [comment]
oke thank youu @njiipanji
